proyectoTercerE/apps/cliente/urls.py
from django.urls import path

from .views import crear_cliente, crear_clientes_predeterminados, index, prueba_búsqueda

# Es necesario este nombre, para ser llamado desde la plantila,
# por ejemplo: {% url 'cliente:index' %}
app_name = "cliente"

urlpatterns = [
    path("", index, name="index"),
    path("crear-clientes-predeterminados/", crear_clientes_predeterminados, name="crear-clientes"),
    path("prueba-búsqueda/", prueba_búsqueda, name="prueba-búsqueda"),
    path("crear/", crear_cliente, name="crear"),
]

proyectoTercerE/apps/venta/urls.py
from django.urls import path

from .views import crear_venta, index, prueba_búsqueda, crear_ventas_predeterminadas, cantidad_ventas_totales

app_name = "venta"

urlpatterns = [
    path("", index, name="index"),
    path("crear-ventas-predeterminadas/", crear_ventas_predeterminadas, name="crear-ventas"),
    path("prueba-búsqueda/", prueba_búsqueda, name="prueba-búsqueda"),
    path("crear/", crear_venta, name="crear"),
    path("cantidad-ventas-totales", cantidad_ventas_totales, name="ventas-totales"),
]

proyectoTercerE/proyectoTercerE/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("cliente/,", include("cliente.urls")),
    path("venta/", include("venta.urls")),
]

proyectoTercerE/apps/cliente/models.py
from django.db import models


class Pais(models.Model):
    nombre = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre

class Ciudad(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True)
    pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True)
    ciudad_residencia = models.ForeignKey(Ciudad, on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return f'{self.nombre} {self.apellido}'

proyectoTercerE/apps/venta/models.py
from django.db import models


class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Ventas(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.SET_NULL, null=True)
    cantidad = models.IntegerField(null=True)

    def __str__(self):
        return f'{self.producto}'

proyectoTercerE/apps/cliente/views.py
from django.shortcuts import redirect, render
from django.urls import reverse

from .models import Cliente, Pais, Ciudad


def index(request):
    clientes_registros = Cliente.objects.all()
    contexto = {"clientes": clientes_registros}
    return render(request, "cliente/index.html", contexto)


def crear_clientes_predeterminados(request):
    from datetime import date

    # Crear instancias de países
    p1 = Pais.objects.create(nombre="Argentina")
    p2 = Pais.objects.create(nombre="Chile")
    p3 = Pais.objects.create(nombre="Uruguay")

    # Crear instancias de ciudades
    c1 = Ciudad.objects.create(nombre="Santa Fe")
    c2 = Ciudad.objects.create(nombre="Santiago de Chile")
    c4 = Ciudad.objects.create(nombre="Montevideo")

    # Crear instancias de clientes
    Cliente.objects.create(nombre="Amorina", apellido="Ocampo", nacimiento=date(2001, 9, 24), pais_origen_id=p1, ciudad_residencia=c1)
    Cliente.objects.create(nombre="Gonzalo", apellido="Pomero", nacimiento=date(2005, 6, 9), pais_origen_id=p2, ciudad_residencia=c2)
    Cliente.objects.create(nombre="Amparo", apellido="Pizzi", nacimiento=date(2001, 9, 20), pais_origen_id=p3, ciudad_residencia=None)
    Cliente.objects.create(nombre="Santiago", apellido="Macagno", nacimiento=date(1999, 1, 7), pais_origen_id=None, ciudad_residencia=c4)

    # url = reverse("cliente:index")
    return redirect("cliente:index")


def prueba_búsqueda(request):
    from datetime import date

    # Búsqueda por país de origen vacío
    clientes_pais = Cliente.objects.filter(pais_origen_id=None)

    # Búsqueda por ciudad de residencia vacío
    clientes_ciudad = Cliente.objects.filter(ciudad_residencia=None)

    contexto = {
        "clientes_pais": clientes_pais,
        "clientes_ciudad": clientes_ciudad
    }
    return render(request, "cliente/resultados_busqueda.html", contexto)


def crear_cliente(request):
    from .form import ClienteForm

    if request.method == "POST":
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("cliente:index"))
    else:  # method == "GET"
        form = ClienteForm()
    return render(request, "cliente/crear.html", {"form": form})

proyectoTercerE/apps/venta/views.py
from django.shortcuts import redirect, render
from django.urls import reverse

from .models import Ventas, Producto

# Create your views here.
def index(request):
    ventas_registradas = Ventas.objects.all()
    contexto = {"ventas": ventas_registradas}
    return render(request, "venta/index.html", contexto)

def crear_ventas_predeterminadas(request):

    # Crear instancias de producto
    p1 = Producto.objects.create(nombre="Taza Cala")
    p2 = Producto.objects.create(nombre="Mate Jacinto")
    p3 = Producto.objects.create(nombre="Tazón Aurora")

    # Crear instancias de ventas
    Ventas.objects.create(producto=p1, cantidad=2)
    Ventas.objects.create(producto=p2, cantidad=1)
    Ventas.objects.create(producto=p3, cantidad=2)

    return redirect("venta:index")

def prueba_búsqueda(request):
    from datetime import date

    # Búsqueda por ventas de dos cantidades de productos
    venta_cantidad = Ventas.objects.filter(cantidad=2)

    contexto = {
        "venta_cantidad": venta_cantidad
    }
    return render(request, "venta/resultados_busqueda.html", contexto)

def cantidad_ventas_totales(request):
    venta_cant_total = Ventas.objects.count()

    contexto = {
        "venta_cant_total": venta_cant_total
    }
    return render(request, "venta/cant_total.html", contexto)

def crear_venta(request):
    from .form import VentaForm

    if request.method == "POST":
        form = VentaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("venta:index"))
    else:  # method == "GET"
        form = VentaForm()
    return render(request, "venta/crear.html", {"form": form})

proyectoTercerE/proyectoTercerE/views.py
from django.shortcuts import render

def index(request):
    return render(request, "index.html")

proyectoTercerE/apps/cliente/templates/cliente/crear.html
{% extends 'base.html' %}

{% block TITULO %}Crear cliente{% endblock %}

{% block CONTENIDO %}

    <form method="post">
    {% csrf_token %}
    
    {{ form.as_p }}

    <button type="submit">Guardar</button>
    </form>

{% endblock %}

proyectoTercerE/apps/cliente/templates/cliente/index.html
{% extends 'base.html' %}

{% block TITULO %}CLIENTES{% endblock %}

{% block CONTENIDO %}
    {% for cliente in clientes %}
        <h2>{{ cliente.nombre }}</h2>
        <p>{{ cliente.apellido }}</p>
        <p>{{ cliente.nacimiento }}</p>
        <p>{{ cliente.pais_origen_id }}</p>
        <p>{{ cliente.ciudad_residencia}}</p>
    {% endfor %}
    
    <a href="{% url 'cliente:crear-clientes' %}">Crear datos de clientes preestablecidos</a>
    <br>
    <a href="{% url 'cliente:prueba-búsqueda' %}">Prueba de búsqueda</a>
    <br>
    <a href="{% url 'cliente:crear' %}">Crear cliente</a>
    <br>
    <a href="{% url 'index' %}">Ir a menú principal</a>
{% endblock %}

proyectoTercerE/apps/cliente/templates/cliente/resultados_busqueda.html
{% extends 'base.html' %}

{% block TITULO %}RESULTADOS DE LA BÚSQUEDA{% endblock %}

{% block CONTENIDO %}
    <h2 style="color:darkkhaki">Búsquedad por país o ciudad vacío</h2>
    <h2>Clientes - país</h2>
    {% for cliente in clientes_pais %}
        <p>{{ cliente }}</p>
    {% endfor %}

    <h2>Clientes - ciudad</h2>
    {% for cliente in clientes_ciudad %}
        <p>{{ cliente }}</p>
    {% endfor %}

    <a href="{% url 'index' %}">Ir a menú principal</a>
{% endblock %}

proyectoTercerE/apps/venta/templates/venta/cant_total.html
{% extends 'base.html' %}

{% block TITULO %}CANTIDAD TOTAL DE VENTAS{% endblock %}

{% block CONTENIDO %}
    <p>{{ venta_cant_total }}</p>
    <a href="{% url 'index' %}">Ir a menú principal</a>
{% endblock %}

proyectoTercerE/apps/venta/templates/venta/crear.html
{% extends 'base.html' %}

{% block TITULO %}Crear venta{% endblock %}

{% block CONTENIDO %}

    <form method="post">
    {% csrf_token %}
    
    {{ form.as_p }}

    <button type="submit">Guardar</button>
    </form>

{% endblock %}

proyectoTercerE/apps/venta/templates/venta/index.html
{% extends 'base.html' %}

{% block TITULO %}VENTAS{% endblock %}

{% block CONTENIDO %}
    {% for venta in ventas %}
        <p>{{ venta.producto }}</p>
        <p>{{ venta.cantidad }}</p>
    {% endfor %}
    
    <a href="{% url 'venta:crear-ventas' %}">Crear datos de ventas preestablecidas</a>
    <br>
    <a href="{% url 'venta:ventas-totales' %}">Ver cantidad de ventas totales</a>
    <br>
    <a href="{% url 'venta:prueba-búsqueda' %}">Prueba de búsqueda</a>
    <br>
    <a href="{% url 'venta:crear' %}">Crear venta</a>
    <br>
    <a href="{% url 'index' %}">Ir a menú principal</a>
{% endblock %}

proyectoTercerE/apps/venta/templates/venta/resultados_busqueda.html
{% extends 'base.html' %}

{% block TITULO %}RESULTADOS DE LA BÚSQUEDA{% endblock %}

{% block CONTENIDO %}
    <h2 style="color:darkkhaki">Búsquedad por venta de dos productos</h2>
    <h2>Venta - Cantidad</h2>
    {% for venta in venta_cantidad %}
        <p>{{ venta }}</p>
    {% endfor %}

    <a href="{% url 'index' %}">Ir a menú principal</a>
{% endblock %}

proyectoTercerE/templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <h1 style="color:darkgreen">

            {% block TITULO %}Bienvenido a mi proyecto de Django{% endblock %}
        </h1>

        {% block CONTENIDO %}{% endblock %}
    </body>
</html>

proyectoTercerE/templates/index.html
{% extends 'base.html' %}

{% block CONTENIDO %}
    <div style="text-align: center; font-size: xx-large;">
        <a href="{% url 'cliente:index' %}">Ir a Clientes</a>
        <br>
        <a href="{% url 'venta:index' %}">Ir a Ventas</a>
    </div>
{% endblock %}